# Generated by Django 4.2.6 on 2023-12-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_person_options_alter_person_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=20, verbose_name='Модель телефона')),
                ('phone_info', models.CharField(max_length=20, verbose_name='Характеристики')),
                ('phone_price', models.CharField(max_length=20, verbose_name='Цена')),
                ('phone_author', models.CharField(max_length=20, verbose_name='Производитель')),
            ],
        ),
    ]
