# Generated by Django 4.2.6 on 2023-12-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_phones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RenameField(
            model_name='phones',
            old_name='phone_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='phones',
            old_name='phone_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='phones',
            old_name='phone_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='phones',
            old_name='phone_price',
            new_name='price',
        ),
    ]
